### Collection GET 
GET http://localhost:3001/api/v1/artists
Accept: text/xml, text/csv

### Collection POST 
POST http://localhost:3001/api/v1/artists
Content-Type: application/json

{
  "name": "Daft Punk",
  "genre": "Electronic"
}

### Item GET 
GET http://localhost:3001/api/v1/artists/37
Accept: text/xml, text/csv

### Item PATCH 
PATCH http://localhost:3001/api/v1/artists/36
Content-Type: application/json

{
  "genre": "Electronic / House"
}


### Item DELETE 
DELETE http://localhost:3001/api/v1/artists/-1




